#!/bin/bash
#------------------------------------------------------------------------------
# /usr/bin/doomsday-init-archives

. /etc/doomsday/doomsday.conf

if [ ! -d $git_path ]
then
  mkdir -p $git_path
  if [ $? -gt 0 ]
  then
    echo "Fatal: error creating folder $git_path"
  fi
fi

if [ ! -d $kernel_path ]
then
  mkdir -p $kernel_path
  if [ $? -gt 0 ]
  then
    echo "Fatal: error creating folder $kernel_path"
  fi
fi

for repo in "${doomsday_git_repos[@]}"
do
    git_folder=$(echo $repo | awk '{print substr($1, 1, length($1)-4)}' | awk -F 'github.com/' '{print $2}' | cut -d'/' -f1)
    echo "Creating folder: $git_path$git_folder"
    mkdir -p $git_path$git_folder 2> /dev/null
    cd $git_path$git_folder
    echo "Initialing $repo"
    git clone $repo 2> /dev/null
done

