#!/bin/bash
#------------------------------------------------------------------------------
# /usr/bin/doomsday-update-archives

. /etc/doomsday/doomsday.conf

repos=($(find $git_path -name .git | awk '{if (NR!=1) {print substr($1, 1, length($1)-4)}}'))

for repo in "${repos[@]}"
do
	echo "======================================================"
        echo "Updating: $repo"
        cd $repo
        branchError=$(git branch | grep ^\*\ *\(HEAD\ detached | wc -l)

        if [ $branchError -eq 1 ]
        then
          echo 'Found detached HEAD in local repository'
          branchGood=$(git branch | grep -iE 'main|master' | awk '{print $1}')
          echo "jumping into $branchGood branch"
          git checkout $(git branch | grep -iE 'main|master' | awk '{print $1}')
        fi
        echo "git pull"
        git pull
        echo "git submodule update"
        git submodule update
	echo "======================================================"
done
echo ""
echo "======================================================"
echo "KERNEL source code"
cd $kernel_path
echo "Scraping Kernel.org: $(wget -O /tmp/kernel.tmp https://www.kernel.org/ 2>&1 | grep -i 'saving')"
URLs=($(grep .tar..z /tmp/kernel.tmp | awk -F 'href="' '{print $2}' | cut -d'"' -f1 | sort | uniq))
echo -e "Found: \n$URLs"
for url in "${URLs[@]}"
do
  wget -c $url
done
echo "======================================================"
rm -f /tmp/kernel.tmp

